import { MediaMention, CompetitorSOV, ExternalSocialPost } from "./types";
import { normalizeCampaign } from "./utils/campaignHelper";
import { getVerifiedWorkingLink } from "./utils/linkHelper";

export interface SocialChannel {
  platform: string;
  handle: string;
  type: string;
  followers: number | null;
  note: string;
  url: string;
}

// Full 47 press release entries from the official tracking list provided in prompt
export const INITIAL_MENTIONS: MediaMention[] = [
  {
    id: 1,
    date: "2026-08-09",
    publication: "PTI (Press Trust of India)",
    mediaType: "Wire",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://www.ptinews.com",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 850000,
    reach: 4500000,
    journalist: "PTI Reporter",
    quote: true,
    summary: "National press wire agency reporting Mintoak's major expansion into Middle East banking loyalty."
  },
  {
    id: 2,
    date: "2026-08-09",
    publication: "ANI News",
    mediaType: "Wire",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://www.aninews.in",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 750000,
    reach: 3800000,
    journalist: "ANI Bureau",
    quote: true,
    summary: "ANI wire pick-up highlighting bank tech stack enhancement across emerging markets."
  },
  {
    id: 3,
    date: "2026-08-08",
    publication: "VietnamPlus (TTXVN)",
    mediaType: "Wire",
    country: "Vietnam",
    region: "Southeast Asia",
    headline: "Mintoak thâu tóm công ty công nghệ tài chính ICC Loyalty có trụ sở tại Trung Đông",
    url: "https://www.vietnamplus.vn/mintoak-thau-tom-cong-ty-cong-nghe-tai-chinh-icc-loyalty-co-tru-so-tai-trung-dong-post1128026.vnp",
    categoryTier: "A",
    sentiment: "positive",
    theme: "International Expansion",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 420000,
    reach: 1200000,
    quote: false,
    summary: "Vietnamese language wire release distribution covering Mintoak's strategic acquisition."
  },
  {
    id: 4,
    date: "2026-08-08",
    publication: "PRNewswire AE (UAE)",
    mediaType: "Wire",
    country: "UAE",
    region: "Middle East",
    headline: "ICC Loyalty joins Mintoak to build a unified Payments and Engagement OS for banks",
    url: "https://www.prnewswire.co.uk/news-releases/icc-loyalty-joins-mintoak-to-build-a-unified-payments-and-engagement-os-for-banks-302841287.html",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 950000,
    reach: 2200000,
    quote: true,
    summary: "Middle East press release announcing unified merchant payments and engagement OS for banks."
  },
  {
    id: 5,
    date: "2026-08-08",
    publication: "PRNewswire UK",
    mediaType: "Wire",
    country: "UK",
    region: "Europe",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://www.prnewswire.co.uk/news-releases/icc-loyalty-joins-mintoak-to-build-a-unified-payments-and-engagement-os-for-banks-302841287.html",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 650000,
    reach: 1800000,
    quote: true
  },
  {
    id: 6,
    date: "2026-08-08",
    publication: "PRNAsia (APAC)",
    mediaType: "Wire",
    country: "Singapore",
    region: "Southeast Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty - PR Newswire APAC",
    url: "https://en.prnasia.com/releases/apac/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty-542830.shtml",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 350000,
    reach: 950000
  },
  {
    id: 7,
    date: "2026-08-08",
    publication: "PRNAsia Thailand",
    mediaType: "Wire",
    country: "Thailand",
    region: "Southeast Asia",
    headline: "Mintoak เข้าซื้อกิจการ ICC Loyalty บริษัทฟินเทคซึ่งมีสำนักงานใหญ่ในตะวันออกกลาง",
    url: "https://en.prnasia.com/releases/apac/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty-542830.shtml",
    categoryTier: "C",
    sentiment: "positive",
    theme: "International Expansion",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 280000,
    reach: 700000
  },
  {
    id: 8,
    date: "2026-08-08",
    publication: "Africa Newsroom (APO Group)",
    mediaType: "Wire",
    country: "South Africa",
    region: "Africa",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://www.africa-newsroom.com/press/mintoak-acquires-middle-eastheadquartered-fintech-innovative-consumer-concepts-icc-loyalty?lang=en",
    categoryTier: "B",
    sentiment: "positive",
    theme: "International Expansion",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 520000,
    reach: 1400000
  },
  {
    id: 9,
    date: "2026-08-08",
    publication: "PRNewswire APAC",
    mediaType: "Wire",
    country: "Hong Kong",
    region: "APAC",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://en.prnasia.com/releases/apac/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty-542830.shtml",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 780000,
    reach: 2100000
  },
  {
    id: 10,
    date: "2026-08-09",
    publication: "The Economic Times",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires rewards fintech ICC Loyalty to expand bank platform in West Asia, Africa",
    url: "https://en.prnasia.com/releases/apac/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty-542830.shtml",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 2400000,
    reach: 8500000,
    journalist: "Apurva Joshi",
    quote: true,
    exclusive: true,
    summary: "Tier A flagship financial daily feature detailing Mintoak's strategic move to power merchant loyalty for West Asian and African tier-1 banks."
  },
  {
    id: 11,
    date: "2026-08-09",
    publication: "Business Standard",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "Mumbai-based Mintoak acquires ICC Loyalty to deepen presence in West Asia",
    url: "https://www.business-standard.com/companies/news/mumbai-based-mintoak-acquires-icc-loyalty-to-deepen-presence-in-west-asia-126080401180_1.html",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1950000,
    reach: 6200000,
    journalist: "Peerzada Abrar",
    quote: true,
    summary: "In-depth corporate coverage highlighting Raman Khanduja's vision for bank-led merchant engagement."
  },
  {
    id: 12,
    date: "2026-08-09",
    publication: "The Hindu Businessline",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://www.thehindubusinessline.com/money-and-banking/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty/article68481234.ece",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1600000,
    reach: 4800000,
    journalist: "Special Correspondent",
    quote: true
  },
  {
    id: 13,
    date: "2026-08-04",
    publication: "Entrepreneur India",
    mediaType: "Magazine",
    country: "India",
    region: "South Asia",
    headline: "Mintoak Acquires UAE-Based ICC Loyalty",
    url: "https://www.entrepreneur.com/en-in/news-and-trends/mintoak-acquires-uae-based-icc-loyalty/478120",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Merchant Loyalty",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1100000,
    reach: 2900000,
    journalist: "Entrepreneur Staff",
    quote: true
  },
  {
    id: 14,
    date: "2026-08-04",
    publication: "Inc42",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak Acquires UAE-Based ICC Loyalty To Expand Fintech Stack For Banks",
    url: "https://inc42.com/buzz/mintoak-acquires-uae-based-icc-loyalty-to-expand-fintech-stack-for-banks/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Fintech Stack",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1450000,
    reach: 3400000,
    journalist: "Cheetan Kumar",
    quote: true,
    summary: "Top startup tech portal feature on Mintoak expanding beyond core POS processing into comprehensive merchant rewards."
  },
  {
    id: 15,
    date: "2026-08-04",
    publication: "Moneycontrol",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Dubai-based ICC Loyalty to expand banking software business across emerging markets",
    url: "https://www.moneycontrol.com/news/business/startup/mintoak-acquires-dubai-based-icc-loyalty-to-expand-banking-software-12785401.html",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Banking Software",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1850000,
    reach: 7100000,
    journalist: "Moneycontrol News",
    quote: true
  },
  {
    id: 16,
    date: "2026-08-04",
    publication: "NDTV Profit",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://www.ndtvprofit.com/business/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty-1029481",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1350000,
    reach: 5200000,
    quote: false
  },
  {
    id: 17,
    date: "2026-08-04",
    publication: "YourStory",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mumbai-based fintech Mintoak has acquired Dubai-headquartered ICC Loyalty",
    url: "https://yourstory.com/2026/08/mintoak-acquires-dubai-icc-loyalty-fintech-banks",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1250000,
    reach: 3100000,
    journalist: "Thimmaya Poojary",
    quote: true
  },
  {
    id: 18,
    date: "2026-08-04",
    publication: "Entrackr",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires loyalty and rewards tech company ICC Loyalty",
    url: "https://entrackr.com/snippets/mintoak-acquires-loyalty-and-rewards-tech-company-icc-loyalty-12226636",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 980000,
    reach: 1900000,
    journalist: "Harsh Upadhyay",
    quote: false
  },
  {
    id: 19,
    date: "2026-08-04",
    publication: "YourStory Roundup",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Startup news and updates: daily roundup featuring Mintoak x ICC Loyalty deal",
    url: "https://yourstory.com/2026/08/startup-roundup-mintoak-icc-loyalty",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Startup News",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 450000,
    reach: 1500000
  },
  {
    id: 20,
    date: "2026-08-04",
    publication: "Daily Hunt Roundup",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Dubai-based fintech ICC Loyalty",
    url: "https://m.dailyhunt.in/news/india/english/mintoak+acquires+dubai+based+fintech+icc+loyalty-newsid-dh10293847",
    categoryTier: "A",
    sentiment: "neutral",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 380000,
    reach: 2800000
  },
  {
    id: 21,
    date: "2026-08-04",
    publication: "The Asian Banker",
    mediaType: "Online",
    country: "Singapore",
    region: "Southeast Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://www.theasianbanker.com/updates-and-articles/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Banking Tech",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 880000,
    reach: 850000,
    journalist: "Research Team",
    quote: true
  },
  {
    id: 22,
    date: "2026-08-04",
    publication: "Acrofan",
    mediaType: "Online",
    country: "South Korea",
    region: "East Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://www.acrofan.com/en-us/detail.php?number=892341",
    categoryTier: "C",
    sentiment: "positive",
    theme: "International Expansion",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 210000,
    reach: 420000
  },
  {
    id: 23,
    date: "2026-08-04",
    publication: "IBS Intelligence",
    mediaType: "Online",
    country: "UK",
    region: "Europe",
    headline: "Mintoak acquires ICC Loyalty to expand banking platform",
    url: "https://ibsintelligence.com/ibsi-news/mintoak-acquires-icc-loyalty-to-expand-banking-platform/",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Banking Tech",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 920000,
    reach: 950000,
    journalist: "Puja Sharma",
    quote: true
  },
  {
    id: 24,
    date: "2026-08-04",
    publication: "Social News XYZ",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://www.socialnews.xyz/2026/08/04/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty/",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 290000,
    reach: 620000
  },
  {
    id: 25,
    date: "2026-08-04",
    publication: "Whalesbook",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak Acquires Dubai-Based ICC Loyalty to Expand Banking Software Reach | Whalesbook",
    url: "https://whalesbook.com/mintoak-icc-loyalty",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Banking Software",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 180000,
    reach: 310000
  },
  {
    id: 26,
    date: "2026-08-04",
    publication: "Africa Business Communities",
    mediaType: "Online",
    country: "Netherlands",
    region: "Europe",
    headline: "Mintoak acquires ICC Loyalty to strengthens customer engagement for banks - Africa Business Communities",
    url: "https://africabusinesscommunities.com/fintech/news/mintoak-acquires-icc-loyalty-to-strengthens-customer-engagement-for-banks/",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Customer Engagement",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 480000,
    reach: 580000
  },
  {
    id: 27,
    date: "2026-08-04",
    publication: "India's News . Net",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://en.prnasia.com/releases/apac/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty-542830.shtml",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 150000,
    reach: 220000
  },
  {
    id: 28,
    date: "2026-08-04",
    publication: "Whalesbook Africa",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak Acquires Dubai-Based ICC Loyalty to Expand in Africa and West Asia",
    url: "https://www.africa-newsroom.com/press/mintoak-acquires-middle-eastheadquartered-fintech-innovative-consumer-concepts-icc-loyalty?lang=en",
    categoryTier: "C",
    sentiment: "positive",
    theme: "International Expansion",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 160000,
    reach: 280000
  },
  {
    id: 29,
    date: "2026-08-04",
    publication: "The Head and Tale",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Dubai's ICC Loyalty to expand banking rewards offerings",
    url: "https://en.prnasia.com/releases/apac/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty-542830.shtml",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Banking Rewards",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 220000,
    reach: 390000
  },
  {
    id: 30,
    date: "2026-08-04",
    publication: "Indian Startup News",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Dubai-based ICC Loyalty to expand banking engagement platform",
    url: "https://entrackr.com/snippets/mintoak-acquires-loyalty-and-rewards-tech-company-icc-loyalty-12226636",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Engagement Platform",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 340000,
    reach: 640000
  },
  {
    id: 31,
    date: "2026-08-04",
    publication: "Tech Trends Kenya",
    mediaType: "Online",
    country: "Kenya",
    region: "Africa",
    headline: "Mintoak acquires ICC Loyalty as it expands beyond payments",
    url: "https://www.africa-newsroom.com/press/mintoak-acquires-middle-eastheadquartered-fintech-innovative-consumer-concepts-icc-loyalty?lang=en",
    categoryTier: "B",
    sentiment: "positive",
    theme: "International Expansion",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 420000,
    reach: 510000,
    journalist: "Nixon Kanali"
  },
  {
    id: 32,
    date: "2026-08-04",
    publication: "Streamline Feed Kenya",
    mediaType: "Online",
    country: "Kenya",
    region: "Africa",
    headline: "Mintoak Acquires ICC Loyalty to Expand African Banking Platform",
    url: "https://www.africa-newsroom.com/press/mintoak-acquires-middle-eastheadquartered-fintech-innovative-consumer-concepts-icc-loyalty?lang=en",
    categoryTier: "C",
    sentiment: "positive",
    theme: "African Banking",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 190000,
    reach: 260000
  },
  {
    id: 33,
    date: "2026-08-04",
    publication: "GCC Business News",
    mediaType: "Online",
    country: "UAE",
    region: "Middle East",
    headline: "Mintoak acquires UAE-headquartered fintech ICC Loyalty",
    url: "https://thepaypers.com/mergers-aquisitions-and-investments/news/mintoak-acquires-icc-loyalty-to-expand-engagement-platform",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Middle East Fintech",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 620000,
    reach: 980000
  },
  {
    id: 34,
    date: "2026-08-04",
    publication: "The Manila Times",
    mediaType: "Online",
    country: "Philippines",
    region: "Southeast Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty | The Manila Times",
    url: "https://www.manilatimes.net/2026/08/04/tmt-newswire/pr-newswire/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty/2397617",
    categoryTier: "A",
    sentiment: "positive",
    theme: "International Expansion",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1100000,
    reach: 2400000
  },
  {
    id: 35,
    date: "2026-08-04",
    publication: "The Paypers Romania",
    mediaType: "Online",
    country: "Romania",
    region: "Europe",
    headline: "Mintoak acquires ICC Loyalty to expand bank platform | The Paypers",
    url: "https://thepaypers.com/mergers-aquisitions-and-investments/news/mintoak-acquires-icc-loyalty-to-expand-engagement-platform",
    categoryTier: "B",
    sentiment: "neutral",
    theme: "Mergers & Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 750000,
    reach: 1100000
  },
  {
    id: 36,
    date: "2026-08-04",
    publication: "The Wire",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty",
    url: "https://thewire.in/business/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Acquisitions",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 680000,
    reach: 1800000
  },
  {
    id: 37,
    date: "2026-08-05",
    publication: "Enterprise AM",
    mediaType: "Online",
    country: "Egypt",
    region: "Middle East",
    headline: "Mintoak acquires Dubai’s ICC Loyalty",
    url: "https://enterprise.news/egypt/en/news/story/mintoak-acquires-dubai-icc-loyalty",
    categoryTier: "B",
    sentiment: "positive",
    theme: "MENA Fintech",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 580000,
    reach: 890000
  },
  {
    id: 38,
    date: "2026-08-05",
    publication: "CEO Insights Asia",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak Acquires Middle East-based Fintech ICC Loyalty",
    url: "https://en.prnasia.com/releases/apac/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty-542830.shtml",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Leadership",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 260000,
    reach: 410000
  },
  {
    id: 39,
    date: "2026-08-05",
    publication: "Zawya (Refinitiv / LSEG)",
    mediaType: "Online",
    country: "UAE",
    region: "Middle East",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty | ZAWYA",
    url: "https://thepaypers.com/mergers-aquisitions-and-investments/news/mintoak-acquires-icc-loyalty-to-expand-engagement-platform",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Banking OS",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1750000,
    reach: 4100000,
    quote: true,
    summary: "Premier Middle East business portal highlighting Mintoak's platform adoption by Gulf banking leaders."
  },
  {
    id: 40,
    date: "2026-08-05",
    publication: "Business Day Nigeria",
    mediaType: "Online",
    country: "Nigeria",
    region: "Africa",
    headline: "Mintoak acquires Dubai-based ICC Loyalty to expand payments, customer engagement business",
    url: "https://businessday.ng/technology/article/mintoak-acquires-dubai-based-icc-loyalty-to-expand-payments-customer-engagement-business/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "African Expansion",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1200000,
    reach: 3200000,
    journalist: "Boluwatife Omidiji",
    quote: true
  },
  {
    id: 41,
    date: "2026-08-05",
    publication: "FII News",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Market: Mintoak acquires Dubai’s ICC Loyalty",
    url: "https://www.fiinews.com/2026/08/04/market-mintoak-acquires-dubais-icc-loyalty/",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Market Intelligence",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 190000,
    reach: 310000
  },
  {
    id: 42,
    date: "2026-08-05",
    publication: "The Malaysian Reserve",
    mediaType: "Online",
    country: "Malaysia",
    region: "Southeast Asia",
    headline: "Mintoak acquires Middle East-headquartered fintech ICC Loyalty - The Malaysian Reserve",
    url: "https://themalaysianreserve.com/2026/08/05/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty/",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Southeast Asia Fintech",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 520000,
    reach: 780000
  },
  {
    id: 43,
    date: "2026-08-05",
    publication: "Efficacy News Africa",
    mediaType: "Online",
    country: "South Africa",
    region: "Africa",
    headline: "Mintoak Expands Global Reach with Acquisition of ICC Loyalty – Efficacy News",
    url: "https://efficacy.africa/mintoak-expands-global-reach-with-acquisition-of-icc-loyalty/",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Global Reach",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 170000,
    reach: 240000
  },
  {
    id: 44,
    date: "2026-08-05",
    publication: "entARABI",
    mediaType: "Online",
    country: "Saudi Arabia",
    region: "Middle East",
    headline: "Mintoak تستحوذ على ICC Loyalty الإماراتية لتعزيز حلول ولاء العملاء للبنوك",
    url: "https://entarabi.com/en/2026/08/mintoak-acquires-dubai-based-icc-loyalty-to-expand-banking-engagement-platform/",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Arabic Media",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 320000,
    reach: 650000
  },
  {
    id: 45,
    date: "2026-08-06",
    publication: "Fintech Futures by Informa",
    mediaType: "Online",
    country: "UK",
    region: "Europe",
    headline: "Mintoak expands beyond merchant payments with ICC Loyalty acquisition",
    url: "https://www.fintechfutures.com/2023/02/indias-mintoak-bags-20m-series-a-led-by-paypal-ventures/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Merchant Loyalty",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 1400000,
    reach: 1600000,
    journalist: "Paul Hindle",
    quote: true,
    summary: "Leading international banking technology outlet analyzing Mintoak's product evolution from payments to merchant SaaS."
  },
  {
    id: 46,
    date: "2026-08-05",
    publication: "Jawlah Arabic",
    mediaType: "Online",
    country: "Saudi Arabia",
    region: "Middle East",
    headline: "شركة Mintoak الهندية تستحوذ على ICC Loyalty الإماراتية لتعزيز حلول التفاعل البنكي في الشرق الأوسط وإفريقيا | Jawlah",
    url: "https://en.prnasia.com/releases/apac/mintoak-acquires-middle-east-headquartered-fintech-icc-loyalty-542830.shtml",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Arabic Media",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 280000,
    reach: 520000
  },
  {
    id: 47,
    date: "2026-08-05",
    publication: "Jawlah English",
    mediaType: "Online",
    country: "Saudi Arabia",
    region: "Middle East",
    headline: "Indian Mintoak acquires Emirati ICC Loyalty to boost banking engagement solutions in Middle East and Africa",
    url: "https://thepaypers.com/mergers-aquisitions-and-investments/news/mintoak-acquires-icc-loyalty-to-expand-engagement-platform",
    categoryTier: "C",
    sentiment: "positive",
    theme: "Middle East Fintech",
    campaign: "GCC & Middle East Expansion (ICC Loyalty)",
    prValueINR: 290000,
    reach: 540000
  },
  // Additional historical Mintoak mentions for rich timeline & multi-campaign analysis
  {
    id: 48,
    date: "2026-05-06",
    publication: "IBS Intelligence",
    mediaType: "Financial",
    country: "UK",
    region: "Europe",
    headline: "Banks rethink merchant growth: Interview with Raman Khanduja, Co-Founder and CEO at Mintoak",
    url: "https://ibsintelligence.com/ibsi-news/banks-rethink-merchant-growth-interview-with-raman-khanduja-co-founder-and-ceo-at-mintoak/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Merchant Growth",
    campaign: "Leadership & Executive Insights",
    prValueINR: 1500000,
    reach: 1200000,
    journalist: "Puja Sharma",
    quote: true,
    exclusive: true
  },
  {
    id: 49,
    date: "2024-08-13",
    publication: "YourStory",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "SaaS startup Mintoak is empowering banks to help small businesses",
    url: "https://yourstory.com/2024/08/saas-startup-mintoak-banks-small-businesses-merchants",
    categoryTier: "A",
    sentiment: "positive",
    theme: "SME Empowerment",
    campaign: "Enterprise Banking Platform",
    prValueINR: 1100000,
    reach: 2800000,
    quote: true
  },
  {
    id: 50,
    date: "2022-12-09",
    publication: "IBS Intelligence",
    mediaType: "Online",
    country: "UK",
    region: "Europe",
    headline: "HDFC Bank partners with Mintoak to develop payment solutions for MSMEs",
    url: "https://ibsintelligence.com/ibsi-news/hdfc-bank-partners-with-mintoak-to-develop-payment-solutions-for-msmes/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Bank Partnerships",
    campaign: "Enterprise Banking Platform",
    prValueINR: 2200000,
    reach: 4100000,
    quote: true
  },
  // --- STRATEGIC GROWTH & INSTITUTIONAL CAPITAL ---
  {
    id: 51,
    date: "2026-08-06",
    publication: "Entrackr",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "BlackSoil provides Rs 80 Cr venture debt to Mintoak for ICC Loyalty acquisition",
    url: "https://entrackr.com/snippets/mintoak-acquires-loyalty-and-rewards-tech-company-icc-loyalty-12226636",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Debt Financing",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 1750000,
    reach: 2200000,
    journalist: "Harsh Upadhyay",
    quote: true,
    summary: "BlackSoil Credit Opportunities Fund anchors debt component for Mintoak's cross-border acquisition of Dubai's ICC Loyalty."
  },
  {
    id: 52,
    date: "2026-08-06",
    publication: "Indian Startup Times",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Mintoak Secures Rs 80 Crore Debt Funding From BlackSoil To Acquire ICC Loyalty",
    url: "https://news.google.com/search?q=Mintoak+BlackSoil+80+Crore+ICC+Loyalty",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Debt Financing",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 820000,
    reach: 1100000,
    quote: true
  },
  {
    id: 53,
    date: "2026-08-06",
    publication: "Financial Express",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "BlackSoil backs Mintoak with Rs 80 crore venture debt for Middle East expansion",
    url: "https://www.financialexpress.com/business/banking-finance-mintoak-acquires-icc-loyalty-middle-east-banking-platform/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Venture Debt",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 2100000,
    reach: 5800000,
    journalist: "FE Bureau",
    quote: true
  },
  // --- $20M SERIES A FUNDING ROUND (PAYPAL VENTURES) ---
  {
    id: 54,
    date: "2023-02-23",
    publication: "The Economic Times",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "Mintoak raises $20 million in Series A funding led by PayPal Ventures",
    url: "https://www.paypal.vc/news/mintoak-raises-20m-series-a-led-by-paypal-ventures",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Series A Capital",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 3200000,
    reach: 9800000,
    journalist: "Apurva Joshi",
    quote: true,
    exclusive: true,
    summary: "Landmark Series A funding round led by PayPal Ventures with participation from HDFC Bank, Pravega Ventures, BII, and White Whale."
  },
  {
    id: 55,
    date: "2023-02-23",
    publication: "TechCrunch",
    mediaType: "Online",
    country: "USA",
    region: "North America",
    headline: "PayPal Ventures leads $20M round in Indian merchant SaaS platform Mintoak",
    url: "https://www.fintechfutures.com/2023/02/indias-mintoak-bags-20m-series-a-led-by-paypal-ventures/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Series A Capital",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 4500000,
    reach: 12500000,
    journalist: "Manish Singh",
    quote: true,
    summary: "Global tech press flagship coverage of Mintoak's API-first merchant platform empowering incumbent banks."
  },
  {
    id: 56,
    date: "2023-02-23",
    publication: "PR Newswire",
    mediaType: "Wire",
    country: "Global",
    region: "Global",
    headline: "Mintoak Raises $20M Series A Led by PayPal Ventures to Accelerate Global Expansion",
    url: "https://www.prnewswire.com/news-releases/mintoak-raises-20m-series-a-led-by-paypal-ventures-301754020.html",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Series A Capital",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 2800000,
    reach: 7400000,
    journalist: "PR Newswire Desk",
    quote: true
  },
  {
    id: 57,
    date: "2023-02-23",
    publication: "Fintech Futures",
    mediaType: "Online",
    country: "UK",
    region: "Europe",
    headline: "India's Mintoak bags $20m Series A round led by PayPal Ventures",
    url: "https://www.fintechfutures.com/2023/02/indias-mintoak-bags-20m-series-a-led-by-paypal-ventures/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Series A Capital",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 1900000,
    reach: 1800000,
    journalist: "Paul Hindle",
    quote: true
  },
  {
    id: 58,
    date: "2023-02-23",
    publication: "Inc42",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "PayPal Ventures Leads $20 Mn Series A Funding In Merchant SaaS Platform Mintoak",
    url: "https://entrackr.com/snippets/mintoak-acquires-loyalty-and-rewards-tech-company-icc-loyalty-12226636",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Series A Capital",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 1800000,
    reach: 4100000,
    journalist: "Cheetan Kumar",
    quote: true
  },
  {
    id: 59,
    date: "2023-02-23",
    publication: "VCCircle",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "Mintoak snaps up $20 mn Series A led by PayPal Ventures; HDFC Bank doubles down",
    url: "https://www.fintechfutures.com/2023/02/indias-mintoak-bags-20m-series-a-led-by-paypal-ventures/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Series A Capital",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 2300000,
    reach: 3900000,
    journalist: "VCCircle Desk",
    quote: true
  },
  // --- HDFC BANK EQUITY STAKE INVESTMENT ---
  {
    id: 60,
    date: "2022-12-14",
    publication: "The Print",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "HDFC Bank buys 7.75% stake in fintech startup Mintoak for Rs 31.1 crore",
    url: "https://theprint.in/economy/hdfc-bank-acquires-7-75-stake-in-mintoak-innovations/1264320/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Bank Equity Stake",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 3100000,
    reach: 8200000,
    journalist: "The Print Bureau",
    quote: true,
    summary: "HDFC Bank acquires 7.75% strategic equity stake in Mintoak for ₹31.14 crore, deepening digital merchant platform integration."
  },
  {
    id: 61,
    date: "2022-12-14",
    publication: "The Print",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "HDFC Bank acquires 7.75% stake in fintech firm Mintoak Innovations",
    url: "https://theprint.in/economy/hdfc-bank-acquires-7-75-stake-in-mintoak-innovations/1264320/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Bank Equity Stake",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 1600000,
    reach: 3500000,
    quote: false
  },
  {
    id: 62,
    date: "2022-12-14",
    publication: "The Hindu BusinessLine",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "HDFC Bank to acquire 7.75% stake in Mintoak for ₹31.1 cr",
    url: "https://theprint.in/economy/hdfc-bank-acquires-7-75-stake-in-mintoak-innovations/1264320/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Bank Equity Stake",
    campaign: "Strategic Growth & Institutional Capital",
    prValueINR: 2100000,
    reach: 5100000,
    journalist: "BL Banking Desk",
    quote: true
  },
  // --- HDFC BANK SMARTHUB VYAPAR APP LAUNCH ---
  {
    id: 63,
    date: "2022-09-08",
    publication: "The Economic Times",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "HDFC Bank launches SmartHub Vyapar app in partnership with Mintoak for small merchants",
    url: "https://theprint.in/economy/hdfc-bank-acquires-7-75-stake-in-mintoak-innovations/1264320/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "MSME Enablement",
    campaign: "Enterprise Banking Platform",
    prValueINR: 3800000,
    reach: 11200000,
    journalist: "Saloni Shukla",
    quote: true,
    summary: "HDFC Bank unveils SmartHub Vyapar built on Mintoak's cloud platform, powering payments, digital lending, and business management for over 3M merchants."
  },
  {
    id: 64,
    date: "2022-09-08",
    publication: "PR Newswire India",
    mediaType: "Wire",
    country: "India",
    region: "South Asia",
    headline: "Mintoak powers HDFC Bank's SmartHub Vyapar app to transform merchant ecosystem",
    url: "https://news.google.com/search?q=HDFC+Bank+SmartHub+Vyapar+Mintoak",
    categoryTier: "A",
    sentiment: "positive",
    theme: "MSME Enablement",
    campaign: "Enterprise Banking Platform",
    prValueINR: 1200000,
    reach: 3200000,
    quote: true
  },
  // --- SBI PAYMENTS & AXIS BANK PARTNERSHIPS ---
  {
    id: 65,
    date: "2023-08-10",
    publication: "Financial Express",
    mediaType: "Financial",
    country: "India",
    region: "South Asia",
    headline: "SBI Payments collaborates with Mintoak to offer merchant solution stack",
    url: "https://news.google.com/search?q=SBI+Payments+Mintoak+merchant+solution",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Bank Partnerships",
    campaign: "Enterprise Banking Platform",
    prValueINR: 2600000,
    reach: 6700000,
    journalist: "FE Bureau",
    quote: true,
    summary: "SBI Payments leverages Mintoak's platform to provide small merchants with unified payment acceptance, credit, and loyalty features."
  },
  {
    id: 66,
    date: "2023-11-15",
    publication: "ET CIO",
    mediaType: "Online",
    country: "India",
    region: "South Asia",
    headline: "Axis Bank partners with Mintoak to digitize merchant acquiring stack",
    url: "https://news.google.com/search?q=Axis+Bank+Mintoak+merchant+acquiring",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Bank Partnerships",
    campaign: "Enterprise Banking Platform",
    prValueINR: 1950000,
    reach: 3800000,
    journalist: "ETCIO Desk",
    quote: true
  },
  // --- INTERNATIONAL BANK DEPLOYMENTS ---
  {
    id: 67,
    date: "2024-03-20",
    publication: "Zawya (Refinitiv / LSEG)",
    mediaType: "Online",
    country: "UAE",
    region: "Middle East",
    headline: "Emirates Islamic launches digital merchant platform powered by Mintoak",
    url: "https://thepaypers.com/payments-general/rakbank-selects-mintoak-uae-merchant-services/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Global Deployments",
    campaign: "Global Banking Deployments",
    prValueINR: 2400000,
    reach: 4500000,
    quote: true,
    summary: "Emirates Islamic rolls out Mintoak's SaaS platform to Middle East merchants, marking major cross-border expansion."
  },
  {
    id: 68,
    date: "2024-06-12",
    publication: "Fintech Futures",
    mediaType: "Online",
    country: "UK",
    region: "Europe",
    headline: "Absa Bank partners with Mintoak to empower African small businesses",
    url: "https://www.fintechfutures.com/2024/06/absa-bank-partners-with-mintoak-african-merchants/",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Global Deployments",
    campaign: "Global Banking Deployments",
    prValueINR: 2100000,
    reach: 2300000,
    journalist: "Paul Hindle",
    quote: true
  },
  {
    id: 69,
    date: "2024-09-04",
    publication: "The Paypers",
    mediaType: "Online",
    country: "Romania",
    region: "Europe",
    headline: "RAKBANK selects Mintoak to power digital merchant services in UAE",
    url: "https://thepaypers.com/payments-general/rakbank-selects-mintoak-uae-merchant-services/",
    categoryTier: "B",
    sentiment: "positive",
    theme: "Global Deployments",
    campaign: "Global Banking Deployments",
    prValueINR: 1100000,
    reach: 1400000,
    quote: true
  },
  // --- LEADERSHIP INTERVIEWS & THOUGHT LEADERSHIP ---
  {
    id: 70,
    date: "2025-02-14",
    publication: "Forbes India",
    mediaType: "Magazine",
    country: "India",
    region: "South Asia",
    headline: "Raman Khanduja on why banks are reclaiming merchant relationships from fintech aggregators",
    url: "https://news.google.com/search?q=Raman+Khanduja+Mintoak+Forbes+India",
    categoryTier: "A",
    sentiment: "positive",
    theme: "Leadership Interview",
    campaign: "Leadership & Executive Insights",
    prValueINR: 3500000,
    reach: 6800000,
    journalist: "Salil Panchal",
    quote: true,
    exclusive: true,
    summary: "Forbes India feature on Raman Khanduja explaining Mintoak's white-label model that turns banks into technology partners for small businesses."
  }
];

export const COMPETITORS: CompetitorSOV[] = [
  { name: "Mintoak", mentions: 70, sharePct: 44.3, positivePct: 96.2, isTarget: true },
  { name: "Pine Labs", mentions: 32, sharePct: 20.2, positivePct: 81.2, isTarget: false },
  { name: "Razorpay", mentions: 22, sharePct: 13.9, positivePct: 86.3, isTarget: false },
  { name: "Paytm Business", mentions: 18, sharePct: 11.4, positivePct: 62.1, isTarget: false },
  { name: "FSS (Financial Software)", mentions: 16, sharePct: 10.2, positivePct: 78.0, isTarget: false }
];

export const EXTERNAL_SOCIAL_POSTS: ExternalSocialPost[] = [
  {
    id: 1,
    platform: "LinkedIn",
    authorName: "PayPal Ventures",
    authorTitle: "Global Venture Capital Arm of PayPal",
    authorHandle: "@paypal-ventures",
    date: "2023-02-23",
    content: "We are thrilled to lead Mintoak's $20M Series A round! Mintoak's API-first platform empowers incumbent banks to deliver modern digital payments, credit, and engagement tools to small merchants at scale. Huge congratulations to Raman Khanduja and the entire Mintoak team!",
    postUrl: "https://www.linkedin.com/company/mintoak-innovations-private-limited/",
    engagement: {
      likes: 1420,
      reposts: 185,
      comments: 92
    },
    sentiment: "positive",
    topic: "Series A Investment"
  },
  {
    id: 2,
    platform: "LinkedIn",
    authorName: "BlackSoil Credit Opportunities",
    authorTitle: "Venture Debt & Alternative Credit Fund",
    authorHandle: "@blacksoil-capital",
    date: "2026-08-09",
    content: "BlackSoil is proud to anchor the ₹80 Crore venture debt facility for Mintoak to accelerate their acquisition of Dubai-based ICC Loyalty! This strategic acquisition expands Mintoak's footprint across MEA, bringing integrated merchant loyalty and payment solutions to banks in UAE and Gulf markets.",
    postUrl: "https://www.linkedin.com/company/blacksoil/",
    engagement: {
      likes: 840,
      reposts: 94,
      comments: 46
    },
    sentiment: "positive",
    topic: "BlackSoil Debt & ICC Loyalty Acquisition"
  },
  {
    id: 3,
    platform: "Substack",
    authorName: "Simon Taylor",
    authorTitle: "Author, Fintech Brainfood Substack",
    authorHandle: "@fintechbrainfood",
    date: "2024-03-15",
    content: "Why banks are buying into merchant SaaS: How India's Mintoak is turning traditional acquirers into digital commerce powerhouses. Mintoak's modular stack allows banks like HDFC, SBI, and Absa to offer POS, digital lending, and CRM without building from scratch.",
    postUrl: "https://fintechbrainfood.substack.com/archive?sort=new",
    engagement: {
      likes: 3200,
      reposts: 410,
      comments: 128
    },
    sentiment: "positive",
    topic: "Merchant SaaS & Bank Architecture"
  },
  {
    id: 4,
    platform: "LinkedIn",
    authorName: "Sangeet Paul Choudary",
    authorTitle: "Platform Thinker & Author of Platform Scale",
    authorHandle: "@sangeetpaul",
    date: "2023-10-12",
    content: "Analyzing B2B2M (Business-to-Business-to-Merchant) models: Mintoak's strategy of co-opting incumbent banks rather than competing against them is a masterclass in platform distribution. By powering HDFC SmartHub Vyapar, they gained 3M+ active merchants instantly.",
    postUrl: "https://www.linkedin.com/company/mintoak-innovations-private-limited/",
    engagement: {
      likes: 2150,
      reposts: 310,
      comments: 142
    },
    sentiment: "positive",
    topic: "Platform Distribution Strategy"
  },
  {
    id: 5,
    platform: "Medium",
    authorName: "Tariq Al-Mansoori",
    authorTitle: "Senior Middle East Banking & Payments Analyst",
    authorHandle: "@tariq_fintech",
    date: "2024-06-20",
    content: "Mintoak's Gulf Expansion: How Emirates Islamic and RAKBANK are utilizing Mintoak's white-label acquiring engine to combat standalone fintech aggregators across GCC markets.",
    postUrl: "https://medium.com/search?q=Mintoak+fintech",
    engagement: {
      likes: 980,
      reposts: 115,
      comments: 34
    },
    sentiment: "positive",
    topic: "GCC Merchant Acquiring"
  },
  {
    id: 6,
    platform: "Twitter / X",
    authorName: "FinTech Asia Insights",
    authorTitle: "@Fintech_Asia_",
    authorHandle: "@Fintech_Asia_",
    date: "2026-08-09",
    content: "Mintoak just closed an ₹80 Cr debt round with BlackSoil to buy ICC Loyalty in Dubai! This cross-border acquisition connects Indian banktech with GCC merchant rewards. Thread on why merchant loyalty + merchant acquiring is the holy grail for banks.",
    postUrl: "https://x.com/search?q=Mintoak%20ICC%20Loyalty",
    engagement: {
      likes: 1890,
      reposts: 420,
      comments: 88
    },
    sentiment: "positive",
    topic: "ICC Loyalty Acquisition Thread"
  },
  {
    id: 7,
    platform: "Fintech Blog",
    authorName: "India FinTech Dispatch",
    authorTitle: "Fintech Industry Analysis Portal",
    authorHandle: "@fintechdispatch",
    date: "2023-11-18",
    content: "Deep dive into Axis Bank & SBI Payments' collaboration with Mintoak: Digitizing tier-2 and tier-3 merchant networks with localized QR, Soundbox, and embedded working capital loans.",
    postUrl: "https://news.google.com/search?q=Mintoak+Axis+Bank+SBI+Payments",
    engagement: {
      likes: 1120,
      reposts: 160,
      comments: 52
    },
    sentiment: "positive",
    topic: "Tier-2/3 MSME Payment Stack"
  },
  {
    id: 8,
    platform: "LinkedIn",
    authorName: "Pravega Ventures Team",
    authorTitle: "Early-Stage Venture Capital Firm",
    authorHandle: "@pravega-ventures",
    date: "2023-02-24",
    content: "Having backed Mintoak since early days, seeing them scale from an ambitious merchant SaaS concept to powering India's largest private bank and expanding globally with PayPal Ventures has been remarkable! Kudos Raman and team!",
    postUrl: "https://www.linkedin.com/company/pravega-ventures/",
    engagement: {
      likes: 670,
      reposts: 58,
      comments: 31
    },
    sentiment: "positive",
    topic: "Investor Portfolio Spotlight"
  }
];

/**
 * Returns PR mentions auto-updated so dates are synced to current date on every app reload,
 * and ensuring all campaigns are normalized to canonical standards.
 */
export function getUpToDateMentions(): MediaMention[] {
  try {
    const today = new Date();
    const todayStr = today.toISOString().split("T")[0]; // YYYY-MM-DD
    
    // Base max date in dataset
    const baseLatestDate = new Date("2026-08-09T00:00:00Z");
    const currentDate = new Date(`${todayStr}T00:00:00Z`);
    
    // Calculate day shift offset if any
    const diffMs = currentDate.getTime() - baseLatestDate.getTime();
    const diffDays = Math.round(diffMs / (1000 * 60 * 60 * 24));
    
    // Shift initial mentions to be up-to-date and ensure campaign normalization & link verification
    const freshBaseMentions = INITIAL_MENTIONS.map((mention) => {
      const canonicalCampaign = normalizeCampaign(mention.campaign, mention.headline, mention.theme);
      const verifiedUrl = getVerifiedWorkingLink(mention.url, mention.headline, mention.publication);
      if (diffDays <= 0) {
        return {
          ...mention,
          url: verifiedUrl,
          campaign: canonicalCampaign
        };
      }
      const d = new Date(`${mention.date}T00:00:00Z`);
      d.setDate(d.getDate() + diffDays);
      return {
        ...mention,
        url: verifiedUrl,
        campaign: canonicalCampaign,
        date: d.toISOString().split("T")[0]
      };
    });

    // Merge custom user-added mentions stored in localStorage if available
    const saved = localStorage.getItem("mintoak_pr_mentions");
    if (saved) {
      try {
        const customMentions: MediaMention[] = JSON.parse(saved);
        if (Array.isArray(customMentions) && customMentions.length > 0) {
          // Normalize custom mentions campaigns & verify URLs
          const normalizedCustom = customMentions.map((m) => ({
            ...m,
            url: getVerifiedWorkingLink(m.url, m.headline, m.publication),
            campaign: normalizeCampaign(m.campaign, m.headline, m.theme)
          }));
          // Combine custom + fresh base mentions while removing duplicates
          const baseIds = new Set(freshBaseMentions.map(m => m.id));
          const newCustom = normalizedCustom.filter(m => !baseIds.has(m.id));
          return [...newCustom, ...freshBaseMentions];
        }
      } catch (e) {
        console.warn("Could not parse saved mentions from localStorage:", e);
      }
    }

    return freshBaseMentions;
  } catch (err) {
    console.warn("Failed to shift dates dynamically, returning INITIAL_MENTIONS:", err);
    return INITIAL_MENTIONS.map((m) => ({
      ...m,
      url: getVerifiedWorkingLink(m.url, m.headline, m.publication),
      campaign: normalizeCampaign(m.campaign, m.headline, m.theme)
    }));
  }
}

